app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog:
    path:      /blog
    defaults:  { _controller: 'AppBundle:Default:test'}

acme_demo_user_all:
    path:  /users
    defaults: { _controller: 'AppBundle:User:all'}
    requirements:
        _method: GET